[package]
name = "story"
version = "0.1.0"
edition = "2021"

[dependencies]
ui.workspace = true
gpui.workspace = true
fake = { version = "2.10.0", features = ["dummy"] }
charts-rs = "0.3"
regex = "1"
chrono = "0.4"
serde = "1"
serde_json = "1"

[lints]
workspace = true
